---
title: "ECNS 560 Project - Bison Population"
author: "Kyle Froisland"
date: "2024-10-16"
output: html_document
---

Load Raw Data/Packages: *Data loaded from path on my local computer
```{r}
library(readr)
library(tidyverse)
library(readxl)
#Bison_numbers <- read_csv("MSU/ECNS 560/Term Project/Data/Bison_numbers_by_the_county National Bison Association.csv")
#hunting_data_tidy <- read_excel("MSU/GitHub/ECNS-560-Term-Project/Data/hunting_data_tidy.xlsx")
```

Create Tidy Version of Population Data:
```{r}
tidy_bison = Bison_numbers |>
  pivot_longer(cols=bison_census2002:bison_census2017, names_to="year", values_to="population") |>
  select(state_code, county, year, population)
```

Cleaning:
```{r}
#Change year Variable in tidy_bison to just the number (remove "bison_census")
tidy_bison_clean = mutate(tidy_bison, year = sapply(str_remove(tidy_bison$year, "bison_census"), function(x) (x[1])))

#define new dataset with by-state population vs by county
bison_data_merge = tidy_bison_clean |>
  group_by(state_code, year) |>
  summarize(total_population = sum(population)) |>
  rename_at(2, ~'year')

#Change column name of year in hunting data, filter to only years that match population data
colnames(hunting_data_tidy)[2] = 'year' 
hunting_data_tidy |>
  filter(year == "2002" | year == "2007" | year == "2012" | year == "2017")

#Ensure that years are numeric
bison_data_merge$year = as.numeric(bison_data_merge$year)
hunting_data_tidy$year = as.numeric(hunting_data_tidy$year)

```

Merge Data Sets:
```{r}
#join with hunting data by state and year as ID
merged_bison_data = left_join(bison_data_merge, hunting_data_tidy, by = c("state_code" = "state_code", "year" = "year"))
```


Load Map Data from Shapefile: 
```{r}
library(sf)
library(tidyverse)
library(tmap)
library(raster)
library(jsonlite)
library(rvest)
library(units)

#Load Habitats:
habitats = st_read("C:/Users/kdfro/Documents/MSU/GitHub/ECNS-560-Term-Project/Data/Bison Range Map/mBISOx_CONUS_Range_2001v1/mBISOx_CONUS_Range_2001v1.shp") |>
  st_make_valid()

#Calculate Area
st_area(habitats)

#Change Units from M^2 to KM^2
set_units(st_area(habitats), km^2)

plot(habitats)

#Load Ranges:
ranges = raster("C:/Users/kdfro/Documents/MSU/GitHub/ECNS-560-Term-Project/Data/USGS Bison Habitat Map/mBISOx_CONUS_HabMap_2001v1/mBISOx_CONUS_HabMap_2001v1.tif")

plot(ranges)

# Specify the path to your HTML file
file_path <- "C:/Users/kdfro/Documents/MSU/GitHub/ECNS-560-Term-Project/Data/USGS Bison Habitat Map/mBISOx_CONUS_HabMap_2001v1/mBISOx_CONUS_HabMap_2001v1.tif.aux.xml"

# Read the HTML content
html_content <- read_html(file_path)

#Load JSON:
json = fromJSON("C:/Users/kdfro/Documents/MSU/GitHub/ECNS-560-Term-Project/Data/USGS Bison Habitat Map/mBISOx_CONUS_HabModel_2001v1.json")


```

Visualizations:
```{r}
graph1_data = merged_bison_data |>
  filter(state_code == "MONTANA" | state_code == "WYOMING" | state_code == "NORTH DAKOTA" | state_code == "SOUTH DAKOTA")

ggplot(graph1_data, aes(x = year, y = total_population)) +
  geom_point() +
  labs(title = "Bison Population by State", x = "Year", y = "Bison Population") +
  facet_wrap(~state_code)
```


Next: (1) figure out how to load in the spacial data (2) need to play around with visualizations. If we both come up with as many different cool plots as we can we can pick and choose best ones.